website:  
  bread-crumbs: false
  page-navigation: true
  sidebar:
    search: true
    collapse-level: 2   # does not work because a page within is opened
    contents:
      - section: "<b>Graphing With GGPlot class</b>"
        contents: lessons/*[0-9]*.qmd
          # - section: "Intro and Setup"
          #   contents: lessons/*01*.qmd  # need * at beginning or quarto will add a menu level 
          # - section: "Lessons"
          #   collapse: false
          #   contents: "lessons/!(01)*.qmd"  # need * at beginning or quarto will add a menu level

language:
  search-box-placeholder: Search All Lessons # does not work...

project:
  render:
  - lessons/[0-9]*.qmd  # only render files whose names start with a number
  type: website
  output-dir: docs

format:
  html:
    page-layout: full
    css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    # css: "_test/qfc_styles.css"
    toc: true
    toc-title: "<b>Lesson Content</b>"
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    # note: you can only include url using text
    include-in-header:
      - text: |
          <link rel = "shortcut icon" href = "https://qfcatmsu.github.io/assets/quarto/qfc_icon.png" />
          <script>mod=true; // menuCollapse=true;</script>
          <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>
          <!--script src="../_test/qfc_styles.js"></script-->
           
editor: visual